config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users do
    resources :achievements
  end

  root 'users#index'

end

app/models/achievement.rb
class Achievement < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :achievements, dependent: :destroy
end

app/controllers/achievements_controller.rb
class AchievementsController < ApplicationController

  def new
    @user = current_user
    @achievement = Achievement.new
  end

  def create
    @user = current_user
    @achievement = @user.achievements.new(achievements_params)
    if @achievement.save
      redirect_to "/users/#{@user.id}"
    else
      render 'new'
    end
  end

  private

  def achievements_params
    params.require(:achievement).permit(:description, :date, :leadership, :efficiency, :mentorship)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @achievements = @user.achievements
    @counts = themes_count(@achievements)
  end

  private

  def themes_count(achievements_array)
    counts = {leadership: 0, efficiency: 0, mentorship: 0}
    achievements_array.each do |achievement|
      counts[:leadership] += 1 if achievement.leadership
      counts[:efficiency] += 1 if achievement.efficiency
      counts[:mentorship] += 1 if achievement.mentorship
    end
    counts
  end

end

app/helpers/achievements_helper.rb
module AchievementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/achievements/new.html.erb
 <h1><%= @user.email %>'s Achievements </h1>

 <%= form_for [@user, @achievement] do |f| %>

  <h2>Description</h2>
   <%= f.text_area :description %></br></br>

  <h2>Date</h2>
   <%= f.date_field(:date) %>

  <h2>Themes</h2>
   <%= f.check_box(:leadership) %>
   <%= f.label(:leadership, "Leadership") %>

   <%= f.check_box(:efficiency) %>
   <%= f.label(:efficiency, "Efficiency") %>

   <%= f.check_box(:mentorship) %>
   <%= f.label(:mentorship, "Mentorship") %>


 </br></br>
 <span id="submit"><%= f.submit %></span>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WinBank</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to 'Sign in', new_user_session_path %>
      <%= link_to 'Sign up', new_user_registration_path %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h1>Employees<h1>

  <% if @users.any? %>
    <% @users.each do |user| %>
      <%= link_to user.email, user_path(user) %>
    <% end %>
  <% end %>

app/views/users/show.html.erb
<h1>WINBANK</h1>
<h2>All your big wins on one page</h2>

<% if @user = current_user %>
  <div id='add-achievement'> <%= link_to "Add Achievement", new_user_achievement_path(@user), class: 'add-achievement' %></div>
<% end %>

<div id="achievements-list">
<h1>Achievements</h1>
<h2>Theme Counts:</h2>
<% @counts.each do |theme, value| %>
  <%= "#{theme.capitalize}: #{value}"  %>
<% end %>

<% if @achievements.any? %>
  <% @achievements.each do |achievement| %>
    <h2> <%= achievement.description %> </h2>
    <%= achievement.date %></br>
    Themes:
    <% if achievement.leadership %>
      Leadership
    <% end %>
    <% if achievement.efficiency %>
      Efficiency
      <% end %>
      <% if achievement.mentorship %>
        Mentorship
        <% end %>
  <% end %>
<% else %>
  You have no achievements yet.
<% end %>

</div>